# general
batch_size: 128
optimizer: sgd
patience: 100
architecture: longfilter
in_channels: 1
max_epoch: 100
exp_name: densenet_small_winlen_256
normalize_spectrums: true 
learning_rate: 0.01
window_len: 256
spec_type: librosa_melspec
dev_step_size: 32
seed: 42
use_scheduler: false
scheduler_step_size: 50
scheduler_gamma: 0.1
dev_metric: age_avg_acc_patients

# categories to train on
categories: 
  - gender
  - age

loss_lambda_age: 1
loss_lambda_gender: 1

age_label2cat:
  twenties: 0.0
  thirties: 1.0
  fourties: 2.0
  fifties: 3.0
  sixties: 4.0

gender_label2cat:
  F: 0.0
  M: 1.0


metadata_fname: '/home/jerpint/Dropbox/voicemd_db/cv_balanced/cv_metadata_balanced_debug.csv'
# Metadata splits
split_type: rand_shuffle
# split_type: shuffled_kfold
# n_splits: 2 # TODO: Enable n_splits for 1
