# general
batch_size: 32
optimizer: sgd
patience: 50
architecture: longfilter
in_channels: 1
max_epoch: 20
exp_name: densenet_small_winlen_256
normalize_spectrums: true 
learning_rate: 0.01
window_len: 256
spec_type: librosa_melspec
dev_step_size: 32
seed: 42

# categories to train on
categories: 
  - gender
  - age

# Metadata splits
metadata_fname: '/home/jerpint/Dropbox/voicemd_db/cv_balanced/cv_metadata_balanced_debug.csv'
# metadata_fname: '../data/voice_clips/cleaned_metadata_filtered_dysphonia.csv'
split_type: shuffled_kfold
n_splits: 2
